#!/bin/sh
set -eu

echo "Adding new site: $1"

echo "Creating images directory"
docker-compose exec --user application "web" mkdir -p //var/www/mediawiki/images/docker/$1

echo "Creating tmp directory"
docker-compose exec --user application "web" mkdir -p //var/www/mediawiki/images/docker/$1/tmp

echo "Creating cache directory"
docker-compose exec --user application "web" mkdir -p //var/www/mediawiki/images/docker/$1/cache

echo "Running install.php script"
docker-compose exec --user application "web" bash //var/www/mediawiki/.docker/installdbs $1

./hosts-add $1.web.mw.localhost
