#!/bin/sh

set -e

echo "Adding new site: $1"

echo "Creating images directory"
docker-compose exec --user application "web" mkdir //var/www/mediawiki/images/docker/$1

echo "Running install.php script"
docker-compose exec --user application "web" bash //var/www/mediawiki/.docker/installdbs $1

echo "Adding site to hosts file"
./addhost $1.web.mw.local.wmftest.net
