#!/bin/sh
set -eu

# create user needed for certain edit actions (only has effect on the first go)
docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.browsertest.yml \
	run --rm web php //var/www/mediawiki/maintenance/createAndPromote.php --wiki default --bureaucrat --sysop --bot lil-seleni test123456! \
	|| true

docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.browsertest.yml \
	run --rm seleniumtests /app/extensions/WikibaseLexeme/node_modules/.bin/wdio /app/extensions/WikibaseLexeme/tests/selenium/wdio.conf.js --waitforTimeout=6000 --mochaOpts.timeout=6000 --hostname selenium  --spec /app/extensions/WikibaseLexeme/tests/selenium/specs/helloworld.js

#--mochaOpts.grep 'can create lexeme with language item not bearing language code'
