#!/bin/sh
set -eu

cd $(dirname $0)

# Create a combined .env file
touch .env
rm .env
./cat-env > .env

# Start Containers
echo "Containers are starting"
docker-compose up -d

# Add document root index file (NOTE: docker-compose lacks a "cp" command)
docker cp config/mediawiki/index.php "$(docker-compose ps -q web)"://var/www/index.php
docker-compose exec "web" chown application:application //var/www/index.php

echo "Waiting for the db servers to finish starting"
docker-compose exec "web" //srv/wait-for-it.sh db-master:3306
docker-compose exec "web" //srv/wait-for-it.sh db-slave:3306

# Reset local hosts file
touch .hosts
rm .hosts

./hosts-add proxy.mw.localhost
./hosts-add phpmyadmin.mw.localhost
./hosts-add graphite.mw.localhost

echo "Setting up log directory"
docker-compose exec "web" mkdir -p //var/log/mediawiki
docker-compose exec "web" chown application:application //var/log/mediawiki

echo "Setting up images directory"
docker-compose exec "web" chown application:application //var/www/mediawiki/images/docker

# Add the default site
./addsite default

# Done
echo "Your development environment is running"
