#!/bin/sh

echo "Running composer install on mediawiki-apache-php5 container"
docker exec -it "mediawikidev_mediawiki-apache-php5_1" composer install --working-dir //var/www/mediawiki

echo "Running install.php script on mediawiki-apache-php7 container"
docker exec -it "mediawikidev_mediawiki-apache-php7_1" bash //var/www/mediawiki/.docker/installdbs