#!/bin/bash

# Allow the user to force and env, but default to php for now..
MWDD_ENV=${MWDD_ENV:-"php"}

# ### PHP only version....
if [[ $MWDD_ENV == "php" ]]
then
    php control/app.php $@
fi

# ### Run everything in docker.. via docker-compose
if [[ $MWDD_ENV == "dc" ]]
then
    # If control container is not already running, then we need to run up
    CONTROL_CONTAINER_ID=$(docker-compose --project-directory . -p mediawiki-docker-dev -f docker-compose/control.yml ps --services --filter "status=running")
    if [ -z "$CONTROL_CONTAINER_ID" ]; then
        docker-compose \
            --project-directory . \
            -p mediawiki-docker-dev \
            -f docker-compose/control.yml \
            up -d --build \
            control
    fi

    # Then run the command
    # This currently runs as root
    # We could pass in the uid and gid, but then by default it would not be able to access the docker socket unless we also tweaked more things
    docker-compose \
        --project-directory . \
        -p mediawiki-docker-dev \
        -f docker-compose/control.yml \
        exec \
        control \
        php control/app.php $@
fi
