#!/bin/bash
# Usage: phpunit-file WIKINAME path/to/test/from/mediawiki/dir
# Example: phpunit-file default tests/phpunit/includes/PageArchiveTest.php
set -eu

PHPUNIT_WIKI=$1

docker-compose exec "web" php //var/www/mediawiki/tests/phpunit/phpunit.php //var/www/mediawiki/${*:2}
