#!/bin/bash
# Usage: phpunit WIKINAME --group=Database
# Example: phpunit default --group=Database
set -eu

PHPUNIT_WIKI=$1

docker-compose exec "web" php //var/www/mediawiki/tests/phpunit/phpunit.php ${*:2}
