#!/bin/sh
# Usage: phpunit WIKINAME path/to/test/from/mediawiki/dir
# Example: phpunit default tests/phpunit/includes/PageArchiveTest.php
set -eu

docker-compose exec "web" php //var/www/mediawiki/tests/phpunit/phpunit.php --wiki $1 //var/www/mediawiki/${*:2}
