#!/usr/bin/env bash
# File for very initial setup of basic MediaWiki code (needed for base development environment)

set -eu

mkdir -p "$DOCKER_MW_PATH"
[[ ! -d $HOME/.composer ]] && mkdir $HOME/.composer

git clone --depth 1 https://gerrit.wikimedia.org/r/mediawiki/core "$DOCKER_MW_PATH"
git clone --depth 1 https://gerrit.wikimedia.org/r/mediawiki/skins/Vector "$DOCKER_MW_PATH"/skins/Vector

cd "$DOCKER_MW_PATH"
docker run -it --rm --user $(id -u):$(id -g) -v $HOME/.composer:/tmp -v $(pwd):/app composer install --ignore-platform-reqs
touch LocalSettings.php
cat > LocalSettings.php <<EOL
<?php
require_once __DIR__ . '/.docker/LocalSettings.php';
wfLoadSkin( 'Vector' );
EOL
