#!/bin/sh

cd $(dirname $0)

# Create a combined .env file
touch ./.env
rm ./.env
cat ./default.env >> .env
sed -i -e '$a\' .env
touch ./local.env
cat ./local.env >> .env
sed -i -e '$a\' .env

# Switch -dev for php vs hhvm (as there is no -dev) for hhvm
if grep -q PHPORHHVM=hhvm .env; then
   echo "DOCKERPHPDEV=" >> .env
else
   echo "DOCKERPHPDEV=-dev" >> .env
fi

# Start Containers
echo "Containers are starting"
docker-compose up -d

# Update composer
echo "Running composer install on the web container"
docker-compose exec --user application "web" composer install --working-dir //var/www/mediawiki

echo "Waiting for the db server to finish starting"
docker-compose exec "web" //srv/wait-for-it.sh db:3306

echo "Adding services to hosts file"
./addhost proxy.mw.local
./addhost phpmyadmin.mw.local
./addhost graphite.mw.local

echo "Setting up log directory"
docker-compose exec "web" mkdir //var/log/mediawiki
docker-compose exec "web" chown application:application //var/log/mediawiki

echo "Setting up images directory"
docker-compose exec "web" chown application:application //var/www/mediawiki/images/docker

# Add the default site
./addsite default

# Done
echo "Your development environment is running"