#!/bin/sh

# Hide the current LocalSettings.php if it exists
if [ -f /var/www/mediawiki/LocalSettings.php ]
then
    mv /var/www/mediawiki/LocalSettings.php /var/www/mediawiki/LocalSettings.php.docker.tmp
fi

# Install the base Mediawiki tables on the db server & remove the generated LocalSettings.php
echo "Running install.php"
php /var/www/mediawiki/maintenance/install.php --dbuser mediawiki --dbpass mwpass --dbname mediawiki --dbserver db --lang en --pass adminpass docker-dev admin
rm /var/www/mediawiki/LocalSettings.php

# Move back the old LocalSettings if we had moved one!
if [ -f /var/www/mediawiki/LocalSettings.php.docker.tmp ]
then
    mv /var/www/mediawiki/LocalSettings.php.docker.tmp /var/www/mediawiki/LocalSettings.php
fi