#!/bin/sh

# Make sure the master db is ready
//srv/wait-for-it.sh db-master:3306

# Hide the current LocalSettings.php if it exists
if [ -f /app/LocalSettings.php ]
then
    mv /app/LocalSettings.php /app/LocalSettings.php.docker.tmp
fi

# Install the base Mediawiki tables on the db server & remove the generated LocalSettings.php
php /app/maintenance/install.php --dbuser root --dbpass toor --dbname $1 --dbserver db-master --lang en --pass dockerpass docker-$1 admin

# Move the generated LocalSettings file, but keep it around incase we want to look at it...
rm /app/LocalSettings.php.docker.lastgenereated
mv /app/LocalSettings.php /app/LocalSettings.php.docker.lastgenereated

# Move back the old LocalSettings if we had moved one!
if [ -f /app/LocalSettings.php.docker.tmp ]
then
    mv /app/LocalSettings.php.docker.tmp /app/LocalSettings.php
fi

# Run update.php too
php /app/maintenance/update.php --wiki $1 --quick
