version: '2.2'

services:

  dps:
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: dps.mw.localhost
    networks:
      dps:
        ipv4_address: 172.0.0.10

  db-master:
    image: ${DB}:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    hostname: db-master.mw.localhost
    dns:
      - 172.0.0.10
    networks:
      - dps
    volumes:
      - sql-data-master:/var/lib/mysql
      - ./config/mysql/master:/tmp/mwdd
    entrypoint: "/tmp/mwdd/entrypoint.sh"
    command: "mysqld"

  mediawiki:
    image: webdevops/php-${WEBSERVER}-dev:${RUNTIMEVERSION}
    user: "${UID}:${GID}"
    environment:
     - WEB_DOCUMENT_ROOT=/var/www
     # Used by various maintenance scripts to find MediaWiki.
     # Also required for /var/www/index.php - https://phabricator.wikimedia.org/T153882
     - MW_INSTALL_PATH=/var/www/mediawiki
     - VIRTUAL_HOST=*.web.mw.localhost
     - PHP_DEBUGGER=xdebug
     - XDEBUG_REMOTE_AUTOSTART=${XDEBUG_REMOTE_AUTOSTART}
     - XDEBUG_REMOTE_HOST=${IDELOCALHOST}
     - XDEBUG_REMOTE_PORT=9000
     - XDEBUG_REMOTE_CONNECT_BACK=0
     - XDEBUG_PROFILER_ENABLE_TRIGGER=1
     - PHP_IDE_CONFIG=serverName=docker
     - PHP_UPLOAD_MAX_FILESIZE=1024M
     - PHP_POST_MAX_SIZE=1024M
    hostname: mediawiki.mw.localhost
    dns:
      - 172.0.0.10
    dns_search:
      - mw.localhost
    networks:
      - dps
    volumes:
     - "${DOCKER_MW_PATH}:/var/www/mediawiki:cached"
     - ./config/mediawiki:/var/www/mediawiki/.docker:ro
     - ./scripts/wait-for-it.sh:/srv/wait-for-it.sh:ro
     - mw-images:/var/www/mediawiki/images/docker:delegated
     - mw-logs:/var/log/mediawiki:delegated

  nginx-proxy:
    # TODO: replace with jwilder/nginx-proxy, once updated
    image: silvanwmde/nginx-proxy:latest
    environment:
      - VIRTUAL_HOST=proxy.mw.localhost
      - HOSTNAMES=.web.mw.localhost      # wildcard name resolution, thanks to DPS
      - HTTP_PORT=${DOCKER_MW_PORT}      # internal port
    ports:
      - "${DOCKER_MW_PORT}:${DOCKER_MW_PORT}"
    hostname: proxy.mw.localhost
    dns:
      - 172.0.0.10
    dns_search:
      - mw.localhost
    networks:
      - dps
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./config/nginx/timeouts.conf:/etc/nginx/conf.d/timeouts.conf:ro

volumes:
  sql-data-master:
  mw-logs:
  mw-images:

networks:
  dps:
    ipam:
      config:
        - subnet: 172.0.0.0/24
