version: '2.2'

services:

  dps:
    image: defreitas/dns-proxy-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: dps.mw.localhost
    networks:
      dps:
        ipv4_address: 172.0.0.10

  nginx-proxy:
    # TODO: replace with jwilder/nginx-proxy, once updated
    image: silvanwmde/nginx-proxy:latest
    environment:
      - VIRTUAL_HOST=proxy.mw.localhost
      - HOSTNAMES=.web.mw.localhost      # wildcard name resolution, thanks to DPS
      - HTTP_PORT=${DOCKER_MW_PORT}      # internal port
    ports:
      - "${DOCKER_MW_PORT}:${DOCKER_MW_PORT}"
    depends_on:
      - dps
    hostname: proxy.mw.localhost
    dns:
      - 172.0.0.10
    dns_search:
      - mw.localhost
    networks:
      - dps
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - ./config/nginx/timeouts.conf:/etc/nginx/conf.d/timeouts.conf:ro

networks:
  dps:
    ipam:
      config:
        - subnet: 172.0.0.0/24
