version: '2.2'

services:
  db-replica:
    image: ${DB}:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    hostname: db-replica.mw.localhost
    dns:
      - 172.0.0.10
    networks:
      - dps
    volumes:
      - sql-data-replica:/var/lib/mysql
      - ./config/mysql/replica:/tmp/mwdd
    entrypoint: "/tmp/mwdd/entrypoint.sh"
    command: "mysqld"

volumes:
  sql-data-replica:
