version: '2.2'

# Service wrapper around what is provided by fresh
# https://github.com/wikimedia/fresh/blob/master/bin/fresh-node10

services:
  mw-quibble:
    image: docker-registry.wikimedia.org/releng/quibble-stretch-php72:latest
    user: "${UID}:${GID}"
    entrypoint: /bin/sh
    command: -c "echo started"
    working_dir: /src
    networks:
      - dps
    dns:
      - 172.0.0.10
    volumes:
      # Only mount code and config, don't mount logs or image
      # TODO is this bit of config even needed?
      - "${DOCKER_MW_PATH}:/workspace/src:cached"
      - ./config/mediawiki:/workspace/src/.docker:ro
      # TODO cache should be mounted from the user machine?
      - mw-quibble-workspace-cache:/workspace/cache
      - mw-quibble-workspace-log:/workspace/log
      - mw-quibble-workspace-ref:/workspace/ref

volumes:
  mw-quibble-workspace-cache:
  mw-quibble-workspace-log:
  mw-quibble-workspace-ref:
