version: '2.2'

services:

  mediawiki:
    image: webdevops/php-${WEBSERVER}-dev:${RUNTIMEVERSION}
    environment:
     # Used by various maintenance scripts to find MediaWiki.
     # Also required for /var/www/index.php - https://phabricator.wikimedia.org/T153882
     - MW_INSTALL_PATH=/app
     - VIRTUAL_HOST=*.web.mw.localhost
     - PHP_DEBUGGER=xdebug
     - XDEBUG_REMOTE_AUTOSTART=${XDEBUG_REMOTE_AUTOSTART}
     - XDEBUG_REMOTE_HOST=${IDELOCALHOST}
     - XDEBUG_REMOTE_PORT=9000
     - XDEBUG_REMOTE_CONNECT_BACK=0
     - XDEBUG_PROFILER_ENABLE_TRIGGER=1
     - PHP_IDE_CONFIG=serverName=docker
     - PHP_UPLOAD_MAX_FILESIZE=1024M
     - PHP_POST_MAX_SIZE=1024M
     # The below env var is not needed by the container, only by MWDD
     - MWDD_LOG_DIR=/var/log/mediawiki/
    hostname: mediawiki.mw.localhost
    depends_on:
      - db-master
      - nginx-proxy
    dns:
      - 172.0.0.10
    dns_search:
      - mw.localhost
    networks:
      - dps
    volumes:
     - "${DOCKER_MW_PATH}:/app:cached"
     - ./config/mediawiki:/app/.docker:ro
     - ./config/wait-for-it.sh:/srv/wait-for-it.sh:ro
     - mw-images:/app/images/docker:delegated
     - mw-logs:/var/log/mediawiki:delegated

volumes:
  mw-logs:
  mw-images:
